import { CloudRain, Flame, TreePine, Waves, Wind, Moon } from 'lucide-react';
import { ThemeConfig, NoiseType } from './types';

export const THEMES: ThemeConfig[] = [
  {
    id: 'rain',
    name: 'Midnight Rain',
    description: 'Soothing raindrops for deep focus.',
    icon: CloudRain,
    primaryColor: 'text-blue-300',
    secondaryColor: 'bg-blue-500/20',
    textColor: 'text-blue-50',
    bgGradient: 'from-slate-900 via-blue-950 to-slate-900',
    noiseType: NoiseType.PINK,
    backgroundImageKeyword: 'rain,window',
    particleType: 'rain',
  },
  {
    id: 'fire',
    name: 'Cozy Campfire',
    description: 'Warm crackling embers for relaxation.',
    icon: Flame,
    primaryColor: 'text-orange-300',
    secondaryColor: 'bg-orange-500/20',
    textColor: 'text-orange-50',
    bgGradient: 'from-gray-900 via-orange-950 to-black',
    noiseType: NoiseType.BROWN,
    backgroundImageKeyword: 'campfire,night',
    particleType: 'fire',
  },
  {
    id: 'forest',
    name: 'Deep Forest',
    description: 'Wind rustling through ancient trees.',
    icon: TreePine,
    primaryColor: 'text-emerald-300',
    secondaryColor: 'bg-emerald-500/20',
    textColor: 'text-emerald-50',
    bgGradient: 'from-green-950 via-teal-950 to-slate-900',
    noiseType: NoiseType.PINK, // Simulates wind
    backgroundImageKeyword: 'forest,mist',
    particleType: 'fireflies',
  },
  {
    id: 'ocean',
    name: 'Ocean Tides',
    description: 'Rhythmic waves hitting the shore.',
    icon: Waves,
    primaryColor: 'text-cyan-300',
    secondaryColor: 'bg-cyan-500/20',
    textColor: 'text-cyan-50',
    bgGradient: 'from-indigo-950 via-cyan-950 to-blue-950',
    noiseType: NoiseType.BROWN,
    backgroundImageKeyword: 'ocean,waves',
    particleType: 'waves',
  },
  {
    id: 'white',
    name: 'Pure Focus',
    description: 'Consistent static to block distractions.',
    icon: Wind,
    primaryColor: 'text-gray-300',
    secondaryColor: 'bg-gray-500/20',
    textColor: 'text-gray-100',
    bgGradient: 'from-gray-800 via-gray-900 to-black',
    noiseType: NoiseType.WHITE,
    backgroundImageKeyword: 'abstract,minimal',
    particleType: 'snow', // Using snow for static-like effect
  },
];